baseUrl: http://localhost:8080
discord:
  token: NDMwNjcxMDIwODY5ODEyMjM0.DaT3Gg.X2ClAfCSHPJfyXfM-NyPPGV6sik # hide!!!!
  clientId: 430671020869812234
twitch:
  clientId: 73d2cc9p19fejvh4m5dkl0ny6p1gp4
