baseUrl: http://localhost:8080
discord:
  clientId: CLIENT_ID
  token: SECRET
twitch:
  clientId: CLIENT_ID
giphy:
  token: SECRET
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/face-collector
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: CLIENT_ID
            client-secret: SECRET
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            scope:
              - guilds
              - identify
            redirectUriTemplate: "{baseUrl}/login/oauth2/code/discord"
            clientName: Face Collector
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: username
